### ISSUE TITLE
Omniauth logout links - error message re devise_scope method

### ISSUE THREAD

**Issue by ashleigh090990** [makersacademy/slack-overflow#12]
We added this in our routes.rb file

```
devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
```

And got the following error when trying to run bin/rake routes

```
/Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:555:in `add_route': Invalid route name, already in use: 'destroy_user_session' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1561:in `add_route'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in `each'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in `match'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:689:in `map_method'
	from /Users/ashleigh/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:650:in `get'
	from /Users/ashleigh/Projects/yelp-clone/config/routes.rb:21:in `block (2 levels) in <top (required)>'
```

I think it's because it's trying to add a duplicate of destroy_user_sessions... Just wondering whether we need it?

**Comment by spike01** [comment]
>Daryl Watson [6:03 PM] 
>It’s because its from a different tutorial, it’s not part of Makers. During the Makers tutorial we already created those routes, so its just duplication. Same for at the bottom of the page where they show you how to do the sign out button.

**Comment by ashleigh090990** [comment]
Thanks :)
