### ISSUE TITLE
Bookmark Manager: Controller extraction problems

### ISSUE THREAD

**Issue by emmabeynon** [makersacademy/slack-overflow#152]
Hi guys,

I'm working through bookmark manager and having trouble with step 25, which is extracting controllers: 

I've pushed the code to Github in its broken state; I've created controller/links.rb, moved the links routes to this file and commented out the original routes in app.rb:
https://github.com/emmabeynon/bookmark-manager/commits/master

I think I've followed the steps but all my tests are failing and I'm getting the below error (I can't even copy it all so it's a sample) - essentially I think what is happening is it thinks the view folder is in the controllers folder and I've no idea why.  Any help appreciated!

```
  14) Tagging links add a single tag to a new link
      Failure/Error: erb(:'links/new')

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/app/controllers/views/links/new.erb
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:210:in `initialize'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:210:in `open'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:210:in `read_template_file'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:76:in `block in initialize'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:77:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:77:in `initialize'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:861:in `new'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:861:in `block in compile_template'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt.rb:88:in `fetch'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:840:in `compile_template'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:821:in `render'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:666:in `erb'
      # /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/app/controllers/links.rb:9:in `block in <class:Bookmarks>'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:60:in `process'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:21:in `visit'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/driver.rb:42:in `visit'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
      # /Users/emma/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/tag_links_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.10471 seconds (files took 1.15 seconds to load)
14 examples, 14 failures

Failed examples:

rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/creating_links_spec.rb:5 # create links add the site's address and title
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/filter_tags_spec.rb:5 # Filter Tags filter links by bubbles tag
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/link_spec.rb:6 # List of links visits webpage and see links
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/link_spec.rb:11 # List of links DataMapper creates a link
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/multiple_tag_links_spec.rb:6 # Adding multiple tags add multiple tags to a new link
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/sign_in_spec.rb:2 # User signs in with correct credentials
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/sign_in_spec.rb:12 # User signs in and fails with incorrect credentials
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/sign_out_spec.rb:2 # User signs out successfully
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/signing_up_spec.rb:2 # User Sign up creates a new user
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/signing_up_spec.rb:14 # User Sign up with incorrect password confirmation
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/signing_up_spec.rb:26 # User Sign up with a blank email address
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/signing_up_spec.rb:35 # User Sign up with an invalid email address
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/signing_up_spec.rb:45 # User Sign up with an already registered email address
rspec /Users/emma/Dropbox (Personal)/Makers_Academy/Projects/Week04/bookmark_manager-01-james/spec/features/tag_links_spec.rb:6 # Tagging links add a single tag to a new link
```

**Comment by spike01** [comment]
Hi Emma,

That is Sinatra's expected behaviour - it assumes the views are in the same folder at the controller. Have a look here and see if there's anything that might help you out:

http://www.sinatrarb.com/configuration.html

**Comment by emmabeynon** [comment]
Got it - thanks!
