### ISSUE TITLE
Problem with database environments

### ISSUE THREAD

**Issue by tcpickard94** [makersacademy/slack-overflow#180]
So it turns out in my app.rb when setting `ENV['RACK_ENV'] ||= 'development'` I missed out the `||=` this meant that my tests were all running in the dev environment and flushing out the database everytime I ran rspec. 

Now that I have included the `||=`, when I run rspec I am getting the error: 
```
/Users/tompickard/.rvm/gems/ruby-2.2.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:63:in `execute_non_query': ERROR:  syntax error at or near "IDENTITY" (DataObjects::SyntaxError)
LINE 1: TRUNCATE TABLE  RESTART IDENTITY;
                                ^
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:63:in `block in execute'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:61:in `execute'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/data_mapper/truncation.rb:111:in `truncate_tables'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/data_mapper/truncation.rb:155:in `block in clean'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/data_mapper/truncation.rb:131:in `disable_referential_integrity'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/data_mapper/truncation.rb:154:in `clean'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:40:in `clean_with'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:91:in `each'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:91:in `clean_with'
	from /Users/tompickard/Documents/Workspace/MakersAcademy/Course/Week4/chitter-challenge/spec/spec_helper.rb:26:in `block (2 levels) in <top (required)>'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:357:in `run'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1724:in `each'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/reporter.rb:77:in `report'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:117:in `run_specs'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:93:in `run'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `load'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `<main>'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tompickard/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

I have tried running `rake db:migrate' and 'rake db:upgrade'  to no avail. 
Any help would be greatly appreciated
Thanks

**Comment by ptolemybarnes** [comment]
Have you created a test database?

**Comment by ptolemybarnes** [comment]
Usually this error is the result of not having migrated the db schema. `rake db:auto_migrate` should fix it. That said, it might be that the migrations are not running against the test database. You can force that by doing: 

`RACK_ENV=test rake db:auto_migrate`

**Comment by drjparry** [comment]
put this line in travis.yml, under 'script', and watch the magic happen...

- bundle exec rake db:auto_migrate RACK_ENV=test

**Comment by tcpickard94** [comment]
Thank you both. I ran Ptolemy's suggestion which cleared the problem locally, then I got the same error on my travis build and David's cleared it up!

**Comment by wirsindpapst** [comment]
Just hand the same issue with my build ... A THOUSAND THANK YOUS IT WORKS NOW
