### ISSUE TITLE
Building Mockito from source outside of an IDE

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/slack-overflow#197]
Has anyone managed to get Mockito running outside of an IDE?  I'm trying to compile it from source, but (possibly because I've forked and cloned the latest beta) it keeps failing during the build testing.  Trying to fix it I have happily installed and built both Gradle and TestNG, the first of which may prove useful and the latter I was intending to use for feature testing anyway.Googling the errors indicates I either need to reduce my heap memory size, or turn off useCompressedOops in the Mockito build configuration.  Unfortunately, I cannot find where the latter is declared without digging through all the class files, since it doesn't appear to be declared in the build.gradle files.  I will find out about the former in a bit and post all this to slack-overflow, but in the meantime:

The error looks like this:

```
:testng:test FAILED
:mockitoJavadoc UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testng:test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

With stack traces from previous errors looking like:

```
Unrecognized VM option 'UseCompressedOops'
Did you mean '(+/-)CheckCompressedOops'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Process 'Gradle Test Executor 13' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 13' finished with non-zero exit value 1
    at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
    at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:91)
    at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:35)
    at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:57)
    at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy59.executionFinished(Unknown Source)
    at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:214)
    at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:312)
    at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
    at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jeremy-Barrass** [comment]
All resolved.
