### ISSUE TITLE
Requests controller / database throwing error

### ISSUE THREAD

**Issue by alexanderwjrussell** [makersacademy/slack-overflow#214]
Hi guys,

I am hoping you will be able to help me. We are getting 
```undefined method `secure?' for #<Request:0x007ffaef568f50>```
when we try to do a post request from the request page. We have the relevant params I think.
```
  post '/requests/:id' do
    @space = Space.first(id: session[:space_id])
    @request = Request.new(user_id: current_user, space_id: current_space, date: params[:date])

    if @request.save
      #success!
    else
      @request.errors.each {|e| puts e}
    end
    redirect to '/requests'
  end
```
It might be failing due to the ```redirect to '/requests'``` but I don't know if it is or why it would. 

Any assistance would be greatly appreciated.

Thanks in advance.

Ali

**Comment by silvabox** [comment]
Can you add a stack trace please?

**Comment by silvabox** [comment]
Also, you are not using the ID parameter defined in the route.

**Comment by alexanderwjrussell** [comment]
```
 # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:270:in `uri'
     # ./app/controllers/requests.rb:26:in `block in <class:MakersBnB>'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/rack_test/browser.rb:61:in `process'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/rack_test/browser.rb:36:in `process_and_follow_redirects'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/rack_test/browser.rb:27:in `submit'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/rack_test/form.rb:79:in `submit'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/rack_test/node.rb:62:in `click'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/node/element.rb:135:in `block in click'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/node/element.rb:135:in `click'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/node/actions.rb:57:in `click_button'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/session.rb:735:in `block (2 levels) in <class:Session>'
     # /Users/alexanderwjrussell/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/make_a_request_spec.rb:12:in `block (2 levels) in <top (required)>'
```

**Comment by silvabox** [comment]
OK, so you've read the error message correctly?  What does it tell you?

**Comment by alexanderwjrussell** [comment]
We have read the error and it seems to point at nothing helpful. Any hints would be great.

**Comment by silvabox** [comment]
It points exactly to the problem

**Comment by alexanderwjrussell** [comment]
```
  1) Request spaces from the space link
     Failure/Error: redirect '/requests'

     NoMethodError:
       undefined method `secure?' for #<Request:0x007ff1e09f9690>
```
You mean?

**Comment by silvabox** [comment]
yes

**Comment by alexanderwjrussell** [comment]
That is what we have been looking at for the last hour. What is it meant to mean?!

**Comment by silvabox** [comment]
It means exactly what it always means.  This is a great opportunity to practise your debugging skills.  Instead of asking me what it means, form a hypothesis yourselves and then investigate.
