### ISSUE TITLE
rsp challenge issue - private method 'select'

### ISSUE THREAD

**Issue by lroliphant** [makersacademy/slack-overflow#31]
Hello,

I am having an issue with calling my 'select' method on my instance of player, that I am passing as a parameter to my game.result method. I am trying to store the result in the result instance variable so that I can call it in my erb file and display the result on the page, but I am getting a private method `select' error when I run rspec and I cannot seem to work out where the problem lies.

My input in Sinatra is:
```
post '/new_game' do
    player = Player.new
    $game = Game.new player
    choice = params[:choice].to_s
    random_choice = $game.computer_choice
    begin
      if choice
        @result = $game.result(player.select(choice))
      else
        @error = 'You have not made a valid selection'
      end
    rescue RuntimeError => @error
    end
  end
Link to repo:
https://github.com/lroliphant/rps-challenge

Player class:
https://github.com/lroliphant/rps-challenge/blob/master/lib/player.rb

Game class:
https://github.com/lroliphant/rps-challenge/blob/master/lib/game.rb
```
Rspec output:

```
Lucys-MacBook-Pro:rps-challenge loliphant$ rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

Start a new game
  homepage directs to start page
  presents a form to enter name
  presents an error page if name field is empty when form submitted
  click a link to start game

Playing game
An expectation of :computer_choice was set on nil. Called from /Users/loliphant/Documents/Projects/weekend_challenges/rps-challenge/spec/feature/play_game_spec.rb:48:in `block (2 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
  can select rock button (FAILED - 1)

Game
  #computer_choice
    allows the computer to give random guess/choice
  #result
    allows player to win if he plays rock and computer plays scissors
    allows player to draw if he plays rock and computer plays rock
    allows player to loose if he plays rock and computer plays paper

Player
  should respond to #select with 1 argument
  #choice
    can select rock as an option
    can select paper as an option
    can select scissors as an option

Failures:

  1) Playing game can select rock button
     Failure/Error: click_button('rock')
     NoMethodError:
       private method `select' called for "rock":String
     # ./lib/game.rb:30:in `win?'
     # ./lib/game.rb:19:in `result'
     # ./lib/rps_app.rb:42:in `block in <class:RSP>'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:26:in `submit'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/form.rb:75:in `submit'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/node.rb:60:in `click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:133:in `block in click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:133:in `click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/actions.rb:37:in `click_button'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/feature/play_game_spec.rb:49:in `block (2 levels) in <top (required)>'

Finished in 0.15649 seconds (files took 1.33 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/feature/play_game_spec.rb:46 # Playing game can select rock button

[Coveralls] Outside the CI environment, not sending data.

```

**Comment by lroliphant** [comment]
It looks like select is an array method, which is possibly causing the 'private' method error I have been getting, so I have changed the rspec error message now, so the above error message is out of date - more screenshots to follow.

**Comment by tansaku** [comment]
any more on this @lroliphant ?  I've adjusted the syntax a little for you ..

**Comment by lroliphant** [comment]
Hi @tansaku, I am now getting a new error message after changing the method name from 'select' to 'choose' but the underlying issue seems to be the same. The rspec error is as follows:
```Lucys-MacBook-Pro:rps-challenge loliphant$ rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

Start a new game
  homepage directs to start page
  presents a form to enter name
  presents an error page if name field is empty when form submitted
  click a link to start game

Playing game
An expectation of :computer_choice was set on nil. Called from /Users/loliphant/Documents/Projects/weekend_challenges/rps-challenge/spec/feature/play_game_spec.rb:48:in `block (2 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
  can choose rock button (FAILED - 1)

Game
  #computer_choice
    allows the computer to give random guess/choice
  #result
    allows player to win if he plays rock and computer plays scissors
    allows player to draw if he plays rock and computer plays rock
    allows player to loose if he plays rock and computer plays paper

Player
  should respond to #choose with 1 argument
  #choice
    can choose rock as an option
    can choose paper as an option
    can choose scissors as an option

Failures:

  1) Playing game can choose rock button
     Failure/Error: click_button('rock')
     NoMethodError:
       undefined method `choose' for "rock":String
     # ./lib/game.rb:30:in `win?'
     # ./lib/game.rb:19:in `result'
     # ./lib/rps_app.rb:41:in `block in <class:RSP>'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:26:in `submit'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/form.rb:75:in `submit'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/rack_test/node.rb:60:in `click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:133:in `block in click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:133:in `click'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/node/actions.rb:37:in `click_button'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # /Users/loliphant/.rvm/gems/ruby-2.2.1/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/feature/play_game_spec.rb:49:in `block (2 levels) in <top (required)>'

Finished in 0.15578 seconds (files took 1.28 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/feature/play_game_spec.rb:46 # Playing game can choose rock button
```

I think the following might be key:
```Playing game
An expectation of :computer_choice was set on nil. Called from /Users/loliphant/Documents/Projects/weekend_challenges/rps-challenge/spec/feature/play_game_spec.rb:48:in `block (2 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
  can choose rock button (FAILED - 1)```

But I'm not sure.

Thanks,

**Comment by tansaku** [comment]
hi @lroliphant the key is this error message: "undefined method `choose' for "rock":String" and which part of your code it points to ... would you mind adding a link to your repo?
