### ISSUE TITLE
Rspec PSQL syntax error

### ISSUE THREAD

**Issue by FaisalChoura** [makersacademy/slack-overflow#33]
```
1) User sign up I can sign up as a new user
     Failure/Error: expect { sign_up }.to change(User, :count).by(1)
     DataObjects::SyntaxError:
       ERROR:  relation "users" does not exist
       LINE 1: SELECT COUNT(*) FROM "users"
                                    ^
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/adapters/dm-do-adapter.rb:20:in `execute_reader'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/adapters/dm-do-adapter.rb:20:in `block in aggregate'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/adapters/dm-do-adapter.rb:14:in `aggregate'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/repository.rb:8:in `aggregate'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/functions.rb:185:in `aggregate'
     # /Users/makerslaptop86/.rvm/gems/ruby-2.2.2/gems/dm-aggregates-1.2.0/lib/dm-aggregates/functions.rb:40:in `count'
     # ./spec/features/user_managment_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.15335 seconds (files took 0.6014 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/features/user_managment_spec.rb:3 # User sign up I can sign up as a new user
```

We got to the end of the adding user accounts stage and we're getting this error.

Here's a link to my repo: https://github.com/FaisalChoura/bookmark_manager

**Comment by tansaku** [comment]
What does this line tell you? 

```ERROR:  relation "users" does not exist```

**Comment by FaisalChoura** [comment]
the relation does not exist. But what is the relation and how do we create it ?

**Comment by tansaku** [comment]
what is 'users' in ```SELECT COUNT(*) FROM "users"```  it's called a relation in the error message - can you think of another word for that this is?

**Comment by FaisalChoura** [comment]
Fixed it !
Just add  ``` require './app/models/user' ```
to data_mapper_setup.rb

**Comment by tansaku** [comment]
well done - but can you also answer my questions before closing this up? :-)

**Comment by tansaku** [comment]
Does it help if you read this? https://en.wikipedia.org/wiki/Object-relational_mapping

also, think about what else happens in data mapper setup?  what does it do to the database?
