### ISSUE TITLE
Chitter database adapter set-up

### ISSUE THREAD

**Issue by Triffanys101** [makersacademy/slack-overflow#40]
Currently trying to set up the databases I need for the chitter test. Everything was working find until I tried to use factory girl within my tests, and all the various add-ons that requires... At least I think that is where it went wrong. Now when I run rspec I get the following error 

``` ruby

/Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:63:in `execute_non_query': ERROR:  syntax error at or near "IDENTITY" (DataObjects::SyntaxError)
LINE 1: TRUNCATE TABLE  RESTART IDENTITY;
                                ^
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:63:in `block in execute'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:61:in `execute'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/data_mapper/truncation.rb:111:in `truncate_tables'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/data_mapper/truncation.rb:155:in `block in clean'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/data_mapper/truncation.rb:131:in `disable_referential_integrity'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/data_mapper/truncation.rb:154:in `clean'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:40:in `clean_with'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:91:in `each'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:91:in `clean_with'
	from /Users/makerslaptop88/Projects/chitter-challenge/spec/spec_helper.rb:26:in `block (2 levels) in <top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:333:in `instance_exec'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:333:in `instance_exec'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:357:in `run'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1559:in `block in run_hooks_with'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1559:in `each'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1559:in `run_hooks_with'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1525:in `with_suite_hooks'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:109:in `block in run_specs'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:62:in `report'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:108:in `run_specs'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:86:in `run'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:70:in `run'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.2/exe/rspec:4:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `<main>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
This is a link to my chitter repo: https://github.com/Triffanys101/chitter-challenge

I think the issue is in my spec-file but i've compared it to my bookmark_manager file and I can't see anything different 

```ruby
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'app/chitter_app.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require './app/data_mapper_setup'
require 'database_cleaner'
require 'factory_girl'
require 'coveralls'
require 'simplecov'

SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
Coveralls.wear!

Capybara.app = Chitter

RSpec.configure do |config|

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.include FactoryGirl::Syntax::Methods

  config.include Capybara::DSL

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```

Any help would be greatly appreciated :)

**Comment by ptolemybarnes** [comment]
Tricky. You might try a few things:
- A database migration.
- If you suspect it's factory girl, remove it from the spec_helper

**Comment by Triffanys101** [comment]
I've just gone back to a previous commit before I made a bunch of changes... Seemed easier than trying to fix whatever was wrong! Thanks though.
