### ISSUE TITLE
Rails Abstract Controller Helpers, Missing Helper Error

### ISSUE THREAD

**Issue by Triffanys101** [makersacademy/slack-overflow#53]
Hey everyone,

I'm currently working through the Yelp challenge and I keep getting the following error:

``` Makerss-MacBook-Pro-59:yelp_clone makerslaptop88$ rspec
/Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers//users/makerslaptop88/projects/week7/yelp/yelp_clone/app/helpers/application_helper.rb_helper.rb (AbstractController::Helpers::MissingHelperError)
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/helpers.rb:144:in `map!'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/helpers.rb:108:in `helper'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/railties/helpers.rb:17:in `inherited'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/test_case.rb:11:in `<class:TestCase>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/test_case.rb:10:in `<module:ActionView>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/test_case.rb:8:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails/example/helper_example_group.rb:9:in `<module:HelperExampleGroup>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails/example/helper_example_group.rb:6:in `<module:Rails>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails/example/helper_example_group.rb:4:in `<module:RSpec>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails/example/helper_example_group.rb:3:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails/example.rb:4:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.3/lib/rspec/rails.rb:12:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/makerslaptop88/projects/week7/yelp/yelp_clone/spec/rails_helper.rb:7:in `<top (required)>'
	from /Users/makerslaptop88/projects/week7/yelp/yelp_clone/spec/features/restaurants_feature_spec.rb:1:in `require'
	from /Users/makerslaptop88/projects/week7/yelp/yelp_clone/spec/features/restaurants_feature_spec.rb:1:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/makerslaptop88/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>' ```

I've tried looking for a solution online but it keeps suggesting I rename a file called sites, or any files with capital letters but I can't find any sites folder or other folders with capitals in my file structure.

**Comment by Triffanys101** [comment]
My terminal was lying I did have a capital!
