### ISSUE TITLE
jasmine-jQuery: TypeError: $ is not a function

### ISSUE THREAD

**Issue by GabyML** [makersacademy/slack-overflow#84]
Hi! 
I'm trying to use jasmine to feature test the Thermostat application, but it seems like SpecRunner can't find my features (or may be something else is going on, please help).

This is the error I'm getting:

TypeError: $ is not a function
TypeError: $ is not a function
    at jasmine.Fixtures.cleanUp (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-jquery.js:82:5)
    at jasmine.Fixtures.load (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-jquery.js:58:10)
    at jasmine.Fixtures.proxyCallTo_ (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-jquery.js:155:29)
    at window.loadFixtures (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-jquery.js:776:27)
    at Object.<anonymous> (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/spec/featureSpec.js:5:5)
    at attemptSync (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-2.3.4/jasmine.js:1789:24)
    at QueueRunner.run (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-2.3.4/jasmine.js:1777:9)
    at QueueRunner.execute (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-2.3.4/jasmine.js:1762:10)
    at Spec.Env.queueRunnerFactory (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-2.3.4/jasmine.js:627:35)
    at Spec.execute (file:///Users/Gabs/Desktop/MakersAcademy/week5/Thermostat/lib/jasmine-2.3.4/jasmine.js:353:10)

I'm using this in my featureSpec.js file:

describe('Thermostat',function(){

  beforeEach(function() {
    jasmine.getFixtures().fixturesPath = ".";
    loadFixtures("index.html");
    $.holdReady(false);
  });

**Comment by stephenlloyd** [comment]
```$ is not a function ``` means at the point you're running the  ```$```  command you don't have jquery loaded by your js.

**Comment by GabyML** [comment]
I just read that it can be fixed by substituting $ for jQuery, but it doesn't seem to work either. How can I load jQuery?

**Comment by trwh** [comment]
For anyone else with this problem; you need to include jQuery before jasmine-jquery in your `SpecRunner.html` file.
