### ISSUE TITLE
Setting up protractor to play nice with Travis CI

### ISSUE THREAD

**Issue by rodcul** [makersacademy/slack-overflow#9]
I'm trying to get protractor running on Travis, but it's (understandably) failing because there is no call to "webdriver-manager start" so there is no selenium server OR indeed http-server for the index.html

Travis build: https://travis-ci.org/makersacademy/todo_challenge/builds/66585511

I've spent 1-2 hours looking for a solution online (including restarting the challenge, previous efforts here: https://github.com/makersacademy/todo_challenge/pull/38)

Thanks!

https://github.com/rodcul/todo_challenge

**Comment by rodcul** [comment]
```
> protractor e2e/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1548:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/runner.js:180:37)
    at /home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/runner.js:268:21
    at _fulfilled (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test --single-run" exited with 1.
0.24s$ node_modules/.bin/protractor e2e/conf.js --browser=firefox
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1548:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/runner.js:180:37)
    at /home/travis/build/makersacademy/todo_challenge/node_modules/protractor/lib/runner.js:268:21
    at _fulfilled (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/travis/build/makersacademy/todo_challenge/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1
The command "node_modules/.bin/protractor e2e/conf.js --browser=firefox" exited with 1.
Done. Your build exited with 1.
```

**Comment by spike01** [comment]
Protractor should start the Selenium instance automatically. Although good point on the local server not being run, I'll amend the README. `npm start` needs to kick off whatever local server you're running, be it `http-server`, Sinatra or a Node server.

**Comment by rodcul** [comment]
Thanks, I just wrapped up for this evening. Will check it out tomorrow!

**Comment by tansaku** [comment]
@rodcul @spike01 is this resolved now?
